version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: idea
    container_name: idea_container
    ports:
      - "8002:8001" # so that we can have SEA and IDEA on the same machine
    env_file:
      - .env
    volumes:
      - idea_persistent_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - LOCAL_DEV=0
      - PQA_HOME=/app/data
      - PAPER_DIRECTORY=/app/data/papers
      - PROMPT_DIRECTORY=/app/data/prompts
    command: uvicorn app:app --host 0.0.0.0 --port 8001
    depends_on:
      - redis
      - db

  db:
    image: pgvector/pgvector:pg17
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  redis:
    image: redis:alpine
    ports:
      - "6380:6379" # so that we can have SEA and IDEA on the same machine
    volumes:
      - idea_redis_data:/data
    command: redis-server --appendonly yes

volumes:
  idea_persistent_data:
  idea_redis_data:
  app-db-data:
