"""add_conversation_and_message_models

Revision ID: 1bd66b9c4029
Revises: 002
Create Date: 2025-08-25 00:20:45.909360

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1bd66b9c4029'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('share_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_session_id'), 'conversation', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversation_share_token'), 'conversation', ['share_token'], unique=True)
    op.create_table('message',
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_type', sa.Enum('CONSOLE', 'MESSAGE', 'IMAGE', 'CODE', 'FILE', 'SYSTEM', name='messagetype'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_systemprompt_user_active', table_name='systemprompt')
    op.create_index(op.f('ix_systemprompt_is_active'), 'systemprompt', ['is_active'], unique=False)
    op.drop_constraint('systemprompt_user_id_fkey', 'systemprompt', type_='foreignkey')
    op.create_foreign_key(None, 'systemprompt', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'systemprompt', type_='foreignkey')
    op.create_foreign_key('systemprompt_user_id_fkey', 'systemprompt', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_systemprompt_is_active'), table_name='systemprompt')
    op.create_index('ix_systemprompt_user_active', 'systemprompt', ['user_id', 'is_active'], unique=False)
    op.drop_table('message')
    op.drop_index(op.f('ix_conversation_share_token'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_session_id'), table_name='conversation')
    op.drop_table('conversation')
    # ### end Alembic commands ###