"""update_message_model_schema

Revision ID: 1fc529effbe2
Revises: 1bd66b9c4029
Create Date: 2025-08-25 01:01:24.158099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc529effbe2'
down_revision = '1bd66b9c4029'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum types first
    messageformat_enum = sa.Enum('OUTPUT', 'PATH', 'BASE64_PNG', 'BASE64_JPEG', 'PYTHON', 'JAVASCRIPT', 'SHELL', 'HTML', 'ACTIVE_LINE', 'EXECUTION', name='messageformat')
    messageformat_enum.create(op.get_bind())
    
    messagerecipient_enum = sa.Enum('USER', 'ASSISTANT', name='messagerecipient')
    messagerecipient_enum.create(op.get_bind())
    
    # Now add the columns
    op.add_column('message', sa.Column('message_format', messageformat_enum, nullable=True))
    op.add_column('message', sa.Column('recipient', messagerecipient_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'recipient')
    op.drop_column('message', 'message_format')
    
    # Drop the enum types
    sa.Enum('USER', 'ASSISTANT', name='messagerecipient').drop(op.get_bind())
    sa.Enum('OUTPUT', 'PATH', 'BASE64_PNG', 'BASE64_JPEG', 'PYTHON', 'JAVASCRIPT', 'SHELL', 'HTML', 'ACTIVE_LINE', 'EXECUTION', name='messageformat').drop(op.get_bind())
    # ### end Alembic commands ###