"""migrate_conversations_from_session_to_user

Revision ID: 901f240d4e80
Revises: d9b987de9ed3
Create Date: 2025-08-31 21:12:30.404432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901f240d4e80'
down_revision = 'd9b987de9ed3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_index('ix_conversation_session_id', table_name='conversation')
    op.create_index(op.f('ix_conversation_user_id'), 'conversation', ['user_id'], unique=False)
    op.create_foreign_key(None, 'conversation', 'user', ['user_id'], ['id'])
    op.drop_column('conversation', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    op.drop_index(op.f('ix_conversation_user_id'), table_name='conversation')
    op.create_index('ix_conversation_session_id', 'conversation', ['session_id'], unique=False)
    op.drop_column('conversation', 'user_id')
    # ### end Alembic commands ###